### ISSUE TITLE
Socks port 偶尔显示为 0

### ISSUE THREAD

**Issue by Sunnyhp** [Dreamacro/clash-dashboard#10]
ClashX 版本：1.9.5
系统：MacOS Mojave 10.14.3
问题：Socks port、http port 都用的是默认的端口，但是 Dashboard 的设置里面这两个端口偶尔显示为 0。
![](https://i.imgur.com/YjcJDJU.png)

**Comment by Dreamacro** [comment]
这不是 dashboard 本身的问题，dashboard 只不过是调用 clash 的 api，并且展示。这里的 0 是因为 clash 所要绑定的 socks5 和 http 端口被占用了。具体请移交 clashx 项目。

**Comment by yyzclyang** [comment]
最近遇到了同样的问题，最后是通过修改基础配置文件而不是自己额外新建的配置文件来解决的。
