### ISSUE TITLE
请对websocket链接进行URLEncode以支持包含特殊字符的密码

### ISSUE THREAD

**Issue by jqyisbest** [Dreamacro/clash-dashboard#101]
**当密码包含特殊字符（比如“;/@”）时，Log和Connection标签页一片空白**
Console报错如下：
![image](https://user-images.githubusercontent.com/16437320/170821708-a4126e61-8e24-4d7d-8420-c7d1dec8f196.png)
查看Network发现生成的websocket链接**未进行URLEncode**
![image](https://user-images.githubusercontent.com/16437320/170821821-5c379336-2cd3-476d-ba2a-c8d10bdf4cac.png)

对照YACD控制面板，其Connection标签页功能正常，其在生成websocket链接时**进行了URLEncode**
![image](https://user-images.githubusercontent.com/16437320/170822465-93fc651e-c7fa-4470-8039-1bb098f0852c.png)

而且，当我把控制面板密码设为不包含特殊字符的密码（即将后三位“;/@”删除）后，Connection标签页和Log标签页均恢复正常了

故此推断是由于未对websocket链接进行URLEncode，导致**当密码包含特殊字符时Log和Connection标签页功能异常**

**Comment by Dreamacro** [comment]
fixed
