### ISSUE TITLE
功能请求：保存 Proxy Group 中的 select 的状态

### ISSUE THREAD

**Issue by ShadowLyin** [Dreamacro/clash-dashboard#11]
目前使用时发现当我使用 Dashboard 选择节点时，clash重启后会重新切换会默认节点，希望能保存选择节点后的状态。

**Comment by Dreamacro** [comment]
这个功能应该没法做，做了就代表你不能使用其他的 GUI 或者直接 API 请求，网页中记录了现在选中状态，但他不知道在其他修改途径中所修改的记录，反而可能会出现更多的问题。

**Comment by cjjdaq** [comment]
为何不是对配置文件直接操作呢？

**Comment by YangtseSu** [comment]
可能的解决方案1:dashboard增加记录功能，每次启动尝试切换到最后选择的节点。
2：api给select增加一个prefered的属性。

**Comment by Dreamacro** [comment]
core 实现了记住选择
