### ISSUE TITLE
[BUG]设置external_controller后，刷新页面仍然会出现弹出窗口请求设置external_controller

### ISSUE THREAD

**Issue by sandwichBob** [Dreamacro/clash-dashboard#119]
在devtools中可以看到，刷新页面后仍然发出了对127.0.0.1的请求。
![image](https://user-images.githubusercontent.com/125239541/220800205-d2427f50-2c04-43b4-aecb-99792b642477.png)
![image](https://user-images.githubusercontent.com/125239541/220800271-6b7a42fa-713b-43eb-895b-242f47a3da09.png)
*系统信息*
![image](https://user-images.githubusercontent.com/125239541/220800375-724cd466-1ab3-454a-b9e2-371b7346c8a1.png)
- 似乎只是在win10的chrome系统会出现bug,在ubuntu chrome上虽然会出现127.0.0.1的请求，但是并不会触发弹窗。这可能与ubuntu chrome会在127.0.0.1立马拒绝连接，但是windows则是一直尝试连接直到超时有关。
- 在配置了external_config之后，设计上似乎不应该继续向127.0.0.1发出请求才对。

**Comment by sandwichBob** [comment]
安卓谷歌浏览器上没有复现这一bug

**Comment by Dreamacro** [comment]
It was fixed.
