### ISSUE TITLE
最新版只要一刷新页面就会弹窗

### ISSUE THREAD

**Issue by dijingkai** [Dreamacro/clash-dashboard#122]
最新版dashboard只要刷新页面就会弹出外部控制配置页面，使用起来挺不方便，望大佬修复，谢谢😁
![image](https://user-images.githubusercontent.com/122948706/221568873-a7cc979f-77af-4797-86c1-76ebc096b055.png)

**Comment by hinak0** [comment]
@Dreamacro last stroage problem seems not be fixed.
#120

**Comment by hinak0** [comment]
you can use this temporarily.
[sandwichBob/clash-dashboard.git](https://github.com/sandwichBob/clash-dashboard.git)

**Comment by hinak0** [comment]
> @Dreamacro last stroage problem seems not be fixed. #120 [0f141b6](https://github.com/Dreamacro/clash-dashboard/commit/0f141b679cb5d623281589444fd71a03c07a2928)

oh ,it was just fixed 25 minutes ago , you can pull latest code to update it .
