### ISSUE TITLE
图标显示异常

### ISSUE THREAD

**Issue by ayanami-desu** [Dreamacro/clash-dashboard#127]
[clash-dashboard](https://github.com/Dreamacro/clash-dashboard)/[src](https://github.com/Dreamacro/clash-dashboard/tree/master/src)/[styles](https://github.com/Dreamacro/clash-dashboard/tree/master/src/styles)/iconfont.scss
中的
```
@font-face {
    font-family: "clash-iconfont";
    src: url('//at.alicdn.com/t/font_841708_ok9czskbhel.ttf?t=1576162884356') format('truetype');
}
```
字体链接已无法访问

**Comment by Dreamacro** [comment]
访问正常的

**Comment by ayanami-desu** [comment]
可能是被拦截规则误伤了
