### ISSUE TITLE
求助：使用反向代理之后日志无法显示？

### ISSUE THREAD

**Issue by wavty0** [Dreamacro/clash-dashboard#132]
未使用反向代理，直连：
![image](https://user-images.githubusercontent.com/117629854/228817347-ca851ad7-e30e-46b8-a35c-a7672442e653.png)
使用 nginx 反向代理后，无法正常显示日志了，是因为 nginx 配置有问题吗？
nginx收到请求之后代理到本地的真正的ui服务端口，nginx配置如下：
![image](https://user-images.githubusercontent.com/117629854/228819307-1e86f591-0a8b-4d92-80b6-0a79ee68513f.png)

**Comment by Dreamacro** [comment]
看控制台吧？日志是 websocket 连接
