### ISSUE TITLE
you need to enable javascript to run this app

### ISSUE THREAD

**Issue by abelzhyb** [Dreamacro/clash-dashboard#136]
访问时一片空白，查看网页源代码，提示信息包含you need to enable javascript to run this app。我打开浏览器的javascript并访问https://www.enable-javascript.com，提示javascript已经开启，但是clash-dashboard仍然是一片空白，是什么原因呢？

**Comment by abelzhyb** [comment]
when I open debug console,It shows http://localhost:9090/src/index.ts was blocked because of a disallowed MIME type "text/plain"

**Comment by twlz0ne** [comment]
```sh
$ grep external-ui ~/.config/clash/config.yaml
external-ui: /path/to/clash-dashboard/dist

$ cd /path/to/clash-dashbaord
$ pnpm install && pnpm build
```

**Comment by Dreamacro** [comment]
use https://github.com/Dreamacro/clash-dashboard/archive/refs/heads/gh-pages.zip instead
