### ISSUE TITLE
能否增加单文件的build

### ISSUE THREAD

**Issue by DUXING130** [Dreamacro/clash-dashboard#145]
能否增加一个单文件版本的项目build，这样在本地使用时无需启用VITE的DEV SERVER

**Comment by Dreamacro** [comment]
#46 不需要 vite serve

**Comment by DUXING130** [comment]
> #46 不需要 vite serve

捣鼓半天，明白了问题的根源，浏览器不允许本地跨域请求资源，导致build出的项目无法正常工作

**Comment by DUXING130** [comment]
虽然我已通过添加一些代码缓解了本地跨域的问题，但还是希望通过将资源打包到单个html文件以彻底解决跨域问题

**Comment by Dreamacro** [comment]
打包成单个 html 无法解决跨域问题，可以把静态资源放到 clash external-ui 目录下

**Comment by DUXING130** [comment]
> 打包成单个 html 无法解决跨域问题，可以把静态资源放到 clash external-ui 目录下

感谢耐心，已成功解决
