### ISSUE TITLE
无法使用nginx proxy manager配置https访问

### ISSUE THREAD

**Issue by qingju32** [Dreamacro/clash-dashboard#147]
services:
  clash:
    image: dreamacro/clash
    container_name: clash
    ports:
      - 7890:7890
      - 9090:9090
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml
      - ./dashboard:/dashboard
    networks:
      - nginx
    restart: unless-stopped

networks:
  nginx:
    external: true

-------------------------------------------
services:
  npm:
    image: jc21/nginx-proxy-manager
    container_name: npm
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    environment:
      - DISABLE_IPV6=true
    networks:
      - nginx
    restart: unless-stopped

networks:
  nginx:
    external: true

-------------------------------------------

开放服务器9090端口后，可以通过  http://ip:9090/ui  访问
在nginx proxy manager中配置反向代理，启用ssl和Websockets Support，可以通过  https://域名/ui  访问登录界面，但是输入ip:9090或clash:9090和密钥无法登录，添加  proxy_set_header Host $host;  无效
由于两个容器在同一个网络下，我尝试了容器名和容器内部ip同样无法访问

我的设想是容器不需要暴露端口给宿主机，通过docker网络使用nginx proxy manager通过不同的子域名访问，来实现https和减少端口开放

直接通过  http://ip:9090/ui  没问题吗，怎么配置呢

**Comment by 717009629** [comment]
![image](https://github.com/Dreamacro/clash-dashboard/assets/16289643/96f59383-0552-4d02-b2fe-0a0ea78da9a2)
我是这样配置的

**Comment by qingju32** [comment]
有用，但是没加/api
