### ISSUE TITLE
外部控制设置127.0.0.1:9090无法配置线上的clash

### ISSUE THREAD

**Issue by esingtse** [Dreamacro/clash-dashboard#15]
我在云服务器上部署了clash-dashboard，并且能够成功运行。在本地浏览器打开dashboard，并在外部控制设置中设置了127.0.0.1:9090，dashboard控制的是我本地的clash。我想通过dashboard去控制云服务器上面的clash，要如何设置？
PS：云服务器上配了Nginx，并将8080端口映射到80端口，服务器方面因为运维人员只给开放80和443端口的权限，无法通过dashboard上配置外网ip:9090去进行外部控制。

**Comment by Dreamacro** [comment]
> 云服务器上配了 Nginx，并将 8080 端口映射到 80 端口

那把 9090 也映射到 80 不就完事了

**Comment by esingtse** [comment]
感谢dalao

**Comment by Scalaaaaaa** [comment]
我的解决方案是,从mac把最新的Country.mmdb和config.yaml复制到你的系统里,然后再下载最新版本的linux上的clash即可.我的linux的clash突然就弹窗了,然后我看了下mac上的config.yaml的最新更新时间,竟然是今天上午,显然linux上的是旧的.
