### ISSUE TITLE
希望移动设备上显示 Connections 选项卡

### ISSUE THREAD

**Issue by Howard-00** [Dreamacro/clash-dashboard#21]

**Comment by Dreamacro** [comment]
移动端屏幕太小了，其实现在显示不显示和屏幕大小有关系，可能横屏有就了

**Comment by Howard-00** [comment]
> 移动端屏幕太小了，其实现在显示不显示和屏幕宽度有关系，可能横屏有就了

可以考虑把 logs 降权吗，毕竟现在 ClashA 有单独的 logs 视图

**Comment by Dreamacro** [comment]
移动端不只是为 clasha 设计的，connections 的东西太多了，不适合窄屏幕看
