### ISSUE TITLE
[Feature Request] Allow using querystring to set hostname, port and secret

### ISSUE THREAD

**Issue by ohsc** [Dreamacro/clash-dashboard#24]
So that I can access different clash controllers with urls.

**Comment by SukkaW** [comment]
Why not requesting API instead of opening in Browser?

**Comment by ohsc** [comment]
> Why not requesting API instead of opening in Browser?

Sorry, that's totally different case.

I want to access dashboard without manually specified any configurations. By supporting specified configurations with querystring,  I can add dashboard to browser's bookmark. So that I can access controller with dashboard directly.

**Comment by thezzisu** [comment]
> > Why not requesting API instead of opening in Browser?
> 
> Sorry, that's totally different case.
> 
> I want to access dashboard without manually specified any configurations. By supporting specified configurations with querystring, I can add dashboard to browser's bookmark. So that I can access controller with dashboard directly.

That's EXACTLY what I needed to manage mutiple clash instances on several servers
