### ISSUE TITLE
建议加一个记住我对“切换时打断包含策略组的连接”打勾状态的功能

### ISSUE THREAD

**Issue by ClarkeCheng** [Dreamacro/clash-dashboard#38]
这个勾我是一直勾上的，但是每次一刷新，勾就没有了。希望网页能记住我对它的设置，一旦勾上了，再刷新勾也不会取消。

**Comment by fcying** [comment]
或者加个默认把这个功能 打勾上的也行...

**Comment by Dreamacro** [comment]
done

**Comment by Seaspirit** [comment]
这个是什么意思啊，不太明白。勾选好还是不勾选好？

**Comment by Dreamacro** [comment]
@Seaspirit 看使用情况，当你在看视频的时候，不勾选好。当你需要切换立马生效的时候，需要勾选。
