### ISSUE TITLE
not working on Archlinux's firefox

### ISSUE THREAD

**Issue by pczmr8v5n454iycf** [Dreamacro/clash-dashboard#39]
The entire page is sometimes just white

**Comment by poly000** [comment]
clash version v1.0.0?
I'm using firefox under archlinux too and I have the same problem

**Comment by poly000** [comment]
same problem on Archlinux's chromium, Windows10's firefox.

**Comment by Dreamacro** [comment]
works fine on macOS firefox

**Comment by poly000** [comment]
are you using a correct configuration?
