### ISSUE TITLE
Is there any official docker image

### ISSUE THREAD

**Issue by greatkeke** [Dreamacro/clash-dashboard#41]
Hi there,
Thanks for your effort to this wonderful project. Is there any official docker image ?

**Comment by Dreamacro** [comment]
pure front-end project don't need docker-image, just download https://github.com/Dreamacro/clash-dashboard/archive/gh-pages.zip and use clash config `external-ui`

**Comment by willzhang** [comment]
> pure front-end project don't need docker-image, just download https://github.com/Dreamacro/clash-dashboard/archive/gh-pages.zip and use clash config `external-ui`


can you add it to this image directory，thanks?

now i must do this
```
mkdir -p /root/.config/clash/
wget https://github.com/Dreamacro/clash-dashboard/archive/gh-pages.zip
unzip gh-pages.zip -d /root/.config/clash/
```
change config
```
external-controller: 0.0.0.0:9090
secret: "123456"
external-ui: clash-dashboard-gh-pages
```
docker run
```
docker run -d --name clash-client \
  --restart always \
  -p 7890:7890 \
  -p 9090:9090 \
  -v /root/.config/clash:/root/.config/clash \
  dreamacro/clash

````
