### ISSUE TITLE
can't view rules, logs, proxies while using clash v1.0.0

### ISSUE THREAD

**Issue by poly000** [Dreamacro/clash-dashboard#42]
OS: archlinux (linux-zen 5.7.8)
`rules, logs, proxies` are all blank

**Comment by Dreamacro** [comment]
works fine on macOS, 1.0.0 has canceled many filed backward compatibility

**Comment by poly000** [comment]
> 
> 
> works fine on macOS, 1.0.0 has canceled many filed backward compatibility
Maybe I'm using the wrong profile and I'll report back to the service provider.
