### ISSUE TITLE
Dashboard cannot work on static page hosting platform or open locally

### ISSUE THREAD

**Issue by isssuer** [Dreamacro/clash-dashboard#51]
## What happened?
I pulled 9fcf2f0 and try to host its files on my own *Coding Pages/Github Pages* so that I can use dashboard without pass GFW first.
## Whats's the problem?
The former hosted pages can't be properly set external controller host and port and it tell me input again and again.
I tried to open it locally and it didn't work, too.
But when I run it with a local HTTP server it worked. Using http://clash.razord.top worked, too.

> In fact, this dashboard worked well in the past with old dashboard version and old clash program.
> I am using Clash v1.0.0.

**Comment by Dreamacro** [comment]
try to use http instead of https

**Comment by isssuer** [comment]
Thank you, it works. but is there any chance that make this dashboard used directly by opening `index.html`? Just like [yacd](https://github.com/haishanh/yacd), which can be open in browser locally without running HTTP server.

**Comment by Dreamacro** [comment]
https://github.com/Dreamacro/clash/wiki/configuration

`external-ui`
