### ISSUE TITLE
最新ACL4SSR_Online_full分流规则导致无法代理COD手游服务器，请求退回版本

### ISSUE THREAD

**Issue by wuchen4588** [Dreamacro/clash-dashboard#55]
最新ACL4SSR_Online_full分流规则导致无法代理COD手游服务器，请求退回版本

**Comment by wuchen4588** [comment]
![Screenshot_2020-09-07-16-47-56-63](https://user-images.githubusercontent.com/60568101/92368295-1fa44080-f12a-11ea-9b70-16d810ec5208.jpg)
![Screenshot_2020-09-07-16-48-18-93](https://user-images.githubusercontent.com/60568101/92368306-22069a80-f12a-11ea-87a7-0682a54664a6.jpg)
本人一直是用openclash来代理服务的，最近更新规则发现COD无法正常游玩，必须走全球直连才可游戏

**Comment by Dreamacro** [comment]
问错地方了吧？
