### ISSUE TITLE
Error: Cannot find module 'react-dev-utils/getPublicUrlOrPath'

### ISSUE THREAD

**Issue by jl0x61** [Dreamacro/clash-dashboard#61]
This error messages are printed by `npm run build`:
```
> clash-dashboard@0.1.0 build /root/clash-dashboard
> GENERATE_SOURCEMAP=false PUBLIC_URL=./ node scripts/build.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'react-dev-utils/getPublicUrlOrPath'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/clash-dashboard/config/paths.js:3:28)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! clash-dashboard@0.1.0 build: `GENERATE_SOURCEMAP=false PUBLIC_URL=./ node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the clash-dashboard@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-29T11_13_44_759Z-debug.log
```
npm and nodejs versions:
```
$ npm -v
6.14.9
$ nodejs -v
v10.19.0
```
Any help will be appreciated!

**Comment by Dreamacro** [comment]
it would better to run `npm ci` instead of `npm install`.

BTW, the nodejs version of github actions and my local nodejs is v15.x. So I'm not sure if the new version of package-lock.json will be incompatible with node 10.

**Comment by nlnjnj** [comment]
> it would better to run `npm ci` instead of `npm install`.
> 
> BTW, the nodejs version of github actions and my local nodejs is v15.x. So I'm not sure if the new version of package-lock.json will be incompatible with node 10.

I got the same issue with nodejs v15.x, while npm ci did work.

**Comment by Dreamacro** [comment]
@nlnjnj can't reproducible on my mbp and `node:alpine` image

**Comment by nlnjnj** [comment]
> @nlnjnj can't reproducible on my mbp and `node:alpine` image

I reproduce this issue when run `npm start` without run `npm install`, so this may more like a user error than code issue.

**Comment by polaiah123** [comment]
> > it would better to run `npm ci` instead of `npm install`.
> > BTW, the nodejs version of github actions and my local nodejs is v15.x. So I'm not sure if the new version of package-lock.json will be incompatible with node 10.
> 
> I got the same issue with nodejs v15.x, while npm ci did work.
