### ISSUE TITLE
firefox下节点字体太小

### ISSUE THREAD

**Issue by ArriettyQAQ** [Dreamacro/clash-dashboard#63]
首先感谢开发者带来这么好用的工具，目前使用中遇到了firefox下节点字体太小的问题，在此反馈一下。

> 经过测试发现， 如将原页面的 `<li class="tags-selected can-click">` 修改为 `<li class="tags-selected can-click" style="font-size: 12px;">` ，此时 Firefox 可以正确响应每一个字号大小。但是基于 Chromium 的 Edge 却只能响应 13px 及以上大小的字体。
如果给 Edge 指定了1~12px 的大小，页面上的字体大小无任何变化。
目前暂不知道是哪个浏览器不正常，非程序员，不懂代码。

下图为4K桌面下的截取的局部图，浏览器自身缩放比例均为100%

Firefox 局部图 [https://i.loli.net/2021/02/01/5UZOLrtm8lzYoSR.png](https://i.loli.net/2021/02/01/5UZOLrtm8lzYoSR.png)
![firefox.png](https://i.loli.net/2021/02/01/5UZOLrtm8lzYoSR.png)

Edge 局部图 [https://i.loli.net/2021/02/01/7uSIZCpKc6jAhqe.png](https://i.loli.net/2021/02/01/7uSIZCpKc6jAhqe.png)
![edge.png](https://i.loli.net/2021/02/01/7uSIZCpKc6jAhqe.png)

---

Firefox 局部图 [https://i.loli.net/2021/02/01/KX613lHv4dyTxfn.png](https://i.loli.net/2021/02/01/KX613lHv4dyTxfn.png)
![Snipaste_2021-02-01_17-54-59.png](https://i.loli.net/2021/02/01/KX613lHv4dyTxfn.png)

Edge 局部图 [https://i.loli.net/2021/02/01/kA71CowFseOYU3z.png](https://i.loli.net/2021/02/01/kA71CowFseOYU3z.png)
![Snipaste_2021-02-01_17-57-06.png](https://i.loli.net/2021/02/01/kA71CowFseOYU3z.png)

----

最后面这两张是4K全屏截图

Firefox 全屏截图 [https://i.loli.net/2021/02/01/RuiO4cdbsok5KfZ.png](https://i.loli.net/2021/02/01/RuiO4cdbsok5KfZ.png)
![Snipaste_2021-02-01_17-34-07.png](https://i.loli.net/2021/02/01/RuiO4cdbsok5KfZ.png)

Edge 全屏截图 [https://i.loli.net/2021/02/01/O3a2dJzvKHisgWm.png](https://i.loli.net/2021/02/01/O3a2dJzvKHisgWm.png)
![Snipaste_2021-02-01_17-33-55.png](https://i.loli.net/2021/02/01/O3a2dJzvKHisgWm.png)

**Comment by Dreamacro** [comment]
> 但是基于 Chromium 的 Edge 却只能响应 13px 及以上大小的字体。

我这里 macOS chrome 是能支持 12px 这个大小的，这个大小的字体 macOS 上还挺正常了

**Comment by Dreamacro** [comment]
close because of long time no response
