### ISSUE TITLE
点击测速没反应

### ISSUE THREAD

**Issue by stdbilly** [Dreamacro/clash-dashboard#65]
部署clash后点击测速没反应，http代理也不能使用
![Screen Shot 2021-02-12 at 18 49 48](https://user-images.githubusercontent.com/22629461/107759379-31d27c80-6d63-11eb-9b90-ef30649dc090.png)

**Comment by liangdong-xjtu** [comment]
> 部署clash后点击测速没反应，http代理也不能使用 ![Screen Shot 2021-02-12 at 18 49 48](https://user-images.githubusercontent.com/22629461/107759379-31d27c80-6d63-11eb-9b90-ef30649dc090.png)

你好，我也遇到这个问题，您最终是怎么解决的呢？

**Comment by mphin** [comment]
2023年9月13日也遇到了同样问题，后来解决了，meta内核：1.节点不支持udp，需要关闭节点配置文件的udp。2.或者切换到P核就可以解决。
