### ISSUE TITLE
策略组页面样式异常

### ISSUE THREAD

**Issue by RikudouPatrickstar** [Dreamacro/clash-dashboard#72]
如图所示，内容少的两行按钮显示为向右对齐。回滚到前几天的 commit [Improve: replace recoil with jotai to reduce bundle](https://github.com/Dreamacro/clash-dashboard/tree/1c9b0669a96943d6c3194aa47c8b08a364199596) 后显示正常。
![屏幕截图 2021-06-26 153801](https://user-images.githubusercontent.com/68163551/123506045-bb407680-d694-11eb-8e88-cde3ff72a554.jpg)

**Comment by Dreamacro** [comment]
fixed
