### ISSUE TITLE
密钥是什么

### ISSUE THREAD

**Issue by ghost** [Dreamacro/clash-dashboard#77]
打开界面时要输入ip, port, key, 这个密钥是要输入什么？
请告诉我，谢谢！

**Comment by KirinRyuuri** [comment]
密钥是你在clash配置文件里面设置的

**Comment by wgxh-cli** [comment]
> @wgxh-cli
> 问这个问题的原因是你没有启动clash程序。
> clash-dashboard只是界面展示与配置程序，需要后台clash支持的。
> clash后台程序有相应的ip,port,key配置，希望这个解答能有用

我启动clash后又试了一遍，还是要求输入密钥

**Comment by clobob** [comment]
> > @wgxh-cli
> > 问这个问题的原因是你没有启动clash程序。
> > clash-dashboard只是界面展示与配置程序，需要后台clash支持的。
> > clash后台程序有相应的ip,port,key配置，希望这个解答能有用
> 
> 我启动clash后又试了一遍，还是要求输入密钥

需要找到clash的配置文件，如果不知在哪里，可以尝试执行 clash.exe -t,通过返回查看配置的所在路径。
然后查看配置中的 external-controller 这一行 和 secret 行
clash dashboard 的相应配置要一致，应该还是配置不匹配
