### ISSUE TITLE
按src ip分组不正确，10.0.0.101会和10.0.0.10的结果混在一起

### ISSUE THREAD

**Issue by LarkinZero** [Dreamacro/clash-dashboard#78]
![截屏2021-08-18 下午5 31 27](https://user-images.githubusercontent.com/6387162/129874961-c54b3b7a-9fe6-416c-a4c7-26095cf84e98.png)

**Comment by Dreamacro** [comment]
应该修好了

**Comment by LarkinZero** [comment]
> 应该修好了

现在问题变成了选了IP分组后，再点击全部，会显示空白。
也就是无法显示全部，除非刷新页面，或者从别的模块再切回来

**Comment by Dreamacro** [comment]
@LarkinZero 再试试

**Comment by LarkinZero** [comment]
> @LarkinZero 再试试

现在看正常了
