### ISSUE TITLE
dashboard 在本地部署的时候，通过 127.0.0.1 访问会一直提示 “编辑外部控制设置”

### ISSUE THREAD

**Issue by everyx** [Dreamacro/clash-dashboard#8]
我放置到 clash 的 external-ui 配置的文件夹中之后，使用 127.0.0.1 访问的时候，第一次弹出设置 OK 之后，能够看到正常内容，但是他会又弹出一次 “编辑外部控制设置” 对话框，直接取消之后可以正常操作。

切换到非 “代理” 菜单下就不会弹出来，但是切换回 “代理” 菜单，就又会弹出来。

**Comment by Dreamacro** [comment]
建议给出控制台的相关错误，dashboard 只会在请求 api 无返回数据或鉴权失败的时候弹出

**Comment by everyx** [comment]
> 
> 
> 建议给出控制台的相关错误，dashboard 只会在请求 api 无返回数据或鉴权失败的时候弹出

请问是 clash 的 “控制台” 日志还是浏览器开发者工具中的 “控制台” 的日志？

**Comment by Dreamacro** [comment]
浏览器的控制台

**Comment by everyx** [comment]
> 
> 
> 浏览器的控制台

看了一下，错误提示如下：

```
TypeError: The expression cannot be converted to return the specified type.
TypeError: u[0] is null
```

**Comment by Dreamacro** [comment]
看一下 network 页红色的请求，把请求结果和请求 api 发一下

**Comment by everyx** [comment]
> 
> 
> 看一下 network 页红色的请求，把请求结果和请求 api 发一下

知道原因了，μblock 屏蔽了 `|http://*/gg1.` 正好会访问到这个地址，关闭 μblock 就好了，麻烦你了，😳

**Comment by 100yuan** [comment]
遇到了一样的问题，把μblock关闭了也还是会出现提示，结果我把地址的http访问改为https访问就好了　https://clash.razord.top/#/proxies

**Comment by John-zhan** [comment]
运行环境：
centos7
wget https://github.com/Dreamacro/clash/releases/download/v1.14.0/clash-linux-amd64-v1.14.0.gz
解压后执行 ./clash -f config.yml
下面是的的配置文件头：具体的服务器配置我没贴
/
# HTTP 代理端口
port: 7890-

# SOCKS5 代理端口
socks-port: 7891-

# Linux 和 macOS 的 redir 代理端口
redir-port: 7892-

# 允许局域网的连接
allow-lan: true

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: debug-
# Clash 的 RESTful API
external-controller: '0.0.0.0:9090'
external-ui: /home/quyi/usr/ui

# RESTful API 的口令
secret: ''-

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# external-ui: folder


proxies:

external-ui 什么也看不到
<img width="974" alt="dashboardERR" src="https://user-images.githubusercontent.com/29363949/229421195-e2442bf6-6119-4de1-969a-cef049f22a10.png">

浏览器日志：
<img width="768" alt="browserlog" src="https://user-images.githubusercontent.com/29363949/229421074-f4b2a2ac-ff4b-4f11-bf2c-d3531344390b.png">
