### ISSUE TITLE
配置好之后，为什么一直无法载入页面呢？

### ISSUE THREAD

**Issue by KISSMonX** [Dreamacro/clash-dashboard#84]
下面是配置和启动信息。
访问这个：http://10.1.4.54:9898/ui  一直无法载入页面。

![image](https://user-images.githubusercontent.com/2876745/141226014-00ce9408-222a-4f9d-88aa-d0d72b0b529b.png)
![image](https://user-images.githubusercontent.com/2876745/141226097-a43a5fb8-9e45-4229-81b2-76455eef1dbf.png)
![image](https://user-images.githubusercontent.com/2876745/141226153-3f544b2c-2975-4073-aed8-f4ae90b0870f.png)

**Comment by KISSMonX** [comment]
有一个 docker 部署的。可以载入页面，但是无法配置 API 链接。
![image](https://user-images.githubusercontent.com/2876745/141226464-1b79ec47-1333-4add-a263-93d5f0cab7dd.png)

**Comment by KISSMonX** [comment]
看了下端口状态，都分配到 TCP6 去了。。。
![image](https://user-images.githubusercontent.com/2876745/141227273-0130ac1a-3ed0-4796-b752-294277dbe4a5.png)

**Comment by KISSMonX** [comment]
防火墙配置问题。

**Comment by GunKneeNeon** [comment]
> 防火墙配置问题。

请问如何这个问题应该改防火墙的什么配置？我这边和你的问题一样，只有tcp6，没有tcp.

**Comment by jerryshadow** [comment]
`sudo systemctl stop iptables.service`
