### ISSUE TITLE
请求 Clash controller API 时报 CORS 错误

### ISSUE THREAD

**Issue by fantasticmao** [Dreamacro/clash-dashboard#89]
似乎是因为浏览器没给加 `-H 'Origin: http://clash.razord.top'` 导致的（也不确定是否是由于我安装的哪个插件导致的......），我们可以在前端显式指定一下么？

![image](https://user-images.githubusercontent.com/20675747/148698741-57a74a95-8e9f-45c3-af2a-d75e0afd4560.png)

![image](https://user-images.githubusercontent.com/20675747/148698997-f5484e20-9e5a-4e69-bf86-2c880d4ccb12.png)

**Comment by miaogaolin** [comment]
可以直接设置 ip 解决下
![image](https://user-images.githubusercontent.com/57740293/151202933-e998e070-733c-47ff-a932-3bb1eea8af86.png)

**Comment by volcanoliu** [comment]
Chrome94会有CORS的策略限制，用IP也没有用，在 chrome://flags/ 中把 Block insecure private network requests 禁用即可。参考：https://kebingzao.com/2021/10/11/chrome-private-cors-error/

**Comment by fantasticmao** [comment]
> Chrome94会有CORS的策略限制，用IP也没有用，在 chrome://flags/ 中把 Block insecure private network requests 禁用即可。参考：https://kebingzao.com/2021/10/11/chrome-private-cors-error/

原来如此！怪不得我换成 Safari 就是正常的......

**Comment by ChenZhongPu** [comment]
> > Chrome94会有CORS的策略限制，用IP也没有用，在 chrome://flags/ 中把 Block insecure private network requests 禁用即可。参考：https://kebingzao.com/2021/10/11/chrome-private-cors-error/
> 
> 原来如此！怪不得我换成 Safari 就是正常的......

目前最新的 Safari 也启用了 CORS 限制。
