### ISSUE TITLE
建议增加 log 的过滤功能

### ISSUE THREAD

**Issue by everyx** [Dreamacro/clash-dashboard#9]
在 yacd 中，支持在搜索框中输入关键词，对日志进行过滤，有时候查日志，比较麻烦，如果能在 dashboard 中搞定就很方便了，希望能够支持此功能。

**Comment by Dreamacro** [comment]
Web 面板的局限在于必须开着面板才能接受到实时的日志，所以在 Web 面板中实际上看不到所有的日志数据，依赖浏览器的搜索功能应该也是个不错的选择？

**Comment by everyx** [comment]
> 
> 
> Web 面板的局限在于必须开着面板才能接受到实时的日志，所以在 Web 面板中实际上看不到所有的日志数据，依赖浏览器的搜索功能应该也是个不错的选择？

的确可以使用浏览器的搜索功能，不过这样看起来比较不直观，如果我想看一下某个 ip 的访问日志的话，需要跳好几次，而过滤了的话，直接就能一页看到，省了按好几次回车的动作 😂

**Comment by Dreamacro** [comment]
现在的日志都是基于纯文本的，所以没啥区别。。。

**Comment by everyx** [comment]
> 
> 
> 现在的日志都是基于纯文本的，所以没啥区别。。。

好的，那我还是用浏览器的搜搜功能吧
