### ISSUE TITLE
通过浏览器访问管理页面无显示

### ISSUE THREAD

**Issue by ABPolaris** [Dreamacro/clash-dashboard#96]
装了clash和dashboard，通过浏览器访问dashboard对应url都是一片空白，但通过web开发者工具查看网络请求都是200响应。运行过pnpm install和pnpm build再运行pnpm start，以及重启电脑也没有解决问题，是浏览器不支持typescript的原因还是别的原因。
有一行报错信息：Uncaught SyntaxError: import not found: useTable [index.tsx:2](http://localhost:3000/home/username/clash-dashboard/src/containers/Connections/index.tsx)
系统是archlinux，浏览器是firefox 99

**Comment by Dreamacro** [comment]
只是想使用的话，下载 https://github.com/Dreamacro/clash-dashboard/tree/gh-pages 就行了
