### ISSUE TITLE
[BUG] 无法从url获取 api 信息

### ISSUE THREAD

**Issue by csj8520** [Dreamacro/clash-dashboard#97]
https://github.com/Dreamacro/clash-dashboard/blob/81362b0816bae1244b858a0773044e490755c29c/src/stores/request.ts#L3

经测试把 react-router-dom 切换回 react-use 可以正常使用
https://github.com/Dreamacro/clash-dashboard/blob/81362b0816bae1244b858a0773044e490755c29c/src/stores/request.ts#L28-L54

useLocation().search  返回值为空字符串
提个小建议： 此处直接使用 window.location.search 不是更方便吗

**Comment by Dreamacro** [comment]
我测试过是能正常用的

**Comment by Dreamacro** [comment]
图里的那个本身就是错误的 url 后面才是正常的

**Comment by csj8520** [comment]
可是跳转路由是不会携带后面的参数的

https://user-images.githubusercontent.com/39072685/165296140-f3838393-c133-4301-a92b-8ea14c62cbb9.mp4

**Comment by Dreamacro** [comment]
@csj8520 早就修复了，刷新一下页面缓存

**Comment by csj8520** [comment]
清除缓存后是可以正常使用了，但是现在的协议和之前的就不一致了。
例如 OpenClash, Clash for OpenWRT 跳转到 clash-dashboard 都会出现协议不兼容的问题
