### ISSUE TITLE
连接信息显示不全

### ISSUE THREAD

**Issue by 462** [Dreamacro/clash-dashboard#98]
如图所示，不缩放窗口无法显示下方的「关闭连接」按钮等内容。
我使用的设备是 1366×768 的分辨率，已最大化窗口，无法滚动连接信息面板。
使用平台是 Windows 10，Chrome 浏览器版本是 `100.0.4896.127`，Dashboard 版本是 63c0bfa。
![2022-05-01_162107](https://user-images.githubusercontent.com/56777282/166138196-7996348d-81dc-4000-bf18-8d6e829e326c.png)

**Comment by Dreamacro** [comment]
fixed
